import { useEffect, useState } from 'react'
import { Brand, Icon, HeroPreview, ProductDemo, journeySteps } from './ProductPreview'
import './ClinisisLanding.css'

const faqs = [
  ['Preciso trocar o sistema da minha clínica?', 'A proposta do Clinisis é complementar o sistema que você já utiliza. Pacientes e atendimentos são o ponto de partida para o acompanhamento. O MVP prevê entrada manual, CSV, API e webhooks; a conexão com cada fornecedor precisa ser validada.'],
  ['Qual é a diferença entre jornada e campanha?', 'Uma jornada acompanha cada paciente a partir de um evento, como uma consulta realizada ou um retorno previsto. Uma campanha reúne um grupo de pacientes para uma ação específica, como retomar o contato com quem está inativo.'],
  ['Como a equipe participa do acompanhamento?', 'As automações cuidam das etapas repetitivas. Respostas que precisam de atenção podem se transformar em tarefas, com contexto e responsável, para a equipe continuar a conversa.'],
  ['Como os resultados serão medidos?', 'O Clinisis foi pensado para conectar oportunidade, contato, agendamento e atendimento. Receita potencial e receita de atendimentos realizados ficam separadas, com a origem da ação registrada. Os números desta página são exemplos.'],
  ['Já posso conhecer o produto?', 'Sim. A demonstração nesta página permite explorar oportunidades, jornadas e resultados com dados fictícios. O produto está em desenvolvimento; disponibilidade de automações e integrações depende da etapa de implantação.'],
]

function getAppUrl() {
  const configured = import.meta.env.VITE_APP_URL
  if (configured && /^https?:\/\//i.test(configured)) return configured.replace(/\/$/, '') + '/login'
  return import.meta.env.DEV ? 'http://localhost:5173/login' : null
}

export default function ClinisisLanding({ loginUrl }) {
  const appUrl = loginUrl ?? getAppUrl()
  const [menuOpen, setMenuOpen] = useState(false)
  useEffect(() => {
    if (!menuOpen) return
    const close = event => { if (event.key === 'Escape') setMenuOpen(false) }
    window.addEventListener('keydown', close)
    return () => window.removeEventListener('keydown', close)
  }, [menuOpen])
  const closeMenu = () => setMenuOpen(false)

  return <div className="clinisis-landing">
    <a className="skip-link" href="#conteudo">Ir para o conteúdo</a>
    <header className="site-header"><div className="site-container header-inner"><a className="brand-link" href="#inicio" aria-label="Clinisis — início" onClick={closeMenu}><Brand /></a><button className="menu-toggle" type="button" aria-expanded={menuOpen} aria-controls="site-navigation" aria-label={menuOpen ? 'Fechar menu' : 'Abrir menu'} onClick={() => setMenuOpen(!menuOpen)}><Icon name={menuOpen ? 'close' : 'menu'} /></button><nav id="site-navigation" className={`site-nav${menuOpen ? ' open' : ''}`} aria-label="Navegação da página"><a href="#solucao" onClick={closeMenu}>A solução</a><a href="#como-funciona" onClick={closeMenu}>Como funciona</a><a href="#integracoes" onClick={closeMenu}>Integrações</a><a href="#duvidas" onClick={closeMenu}>Dúvidas</a>{appUrl && <a className="login-link" href={appUrl}>Entrar <Icon name="arrow" size={14} /></a>}<a className="button button-dark nav-cta" href="#produto" onClick={closeMenu}>Conhecer o Clinisis <Icon name="arrow" size={15} /></a></nav></div></header>
    <main id="conteudo">
      <section className="hero-section" id="inicio"><div className="site-container hero-grid"><div className="hero-copy"><span className="hero-eyebrow"><i />AUTOMAÇÃO DO RELACIONAMENTO COM PACIENTES</span><h1>Sua clínica não perde pacientes <span>depois da consulta.</span></h1><p>Automatize o acompanhamento pós-consulta, mantenha o paciente próximo e transforme cada atendimento em um novo relacionamento.</p><div className="hero-buttons"><a className="button button-dark" href="#produto">Quero conhecer o sistema <Icon name="arrow" size={18} /></a><a className="text-link" href="#como-funciona"><span className="play-icon">▷</span> Veja como funciona</a></div><span className="hero-reassurance"><Icon name="link" size={15} /> Pensado para complementar o sistema da sua clínica.</span></div><HeroPreview /></div><div className="site-container benefit-strip"><span>O cuidado segue.<br /><strong>Sua clínica cresce junto.</strong></span>{[['people', 'Mais pacientes acompanhados'], ['clock', 'Menos tarefas manuais'], ['calendar', 'Mais oportunidades de retorno'], ['message', 'Relacionamento contínuo']].map(([icon, label]) => <div key={label}><Icon name={icon} size={21} /><span>{label}</span></div>)}</div></section>
      <section className="site-container problem-section" id="solucao"><div className="problem-heading"><span className="section-label">UM PROBLEMA QUE A SUA EQUIPE CONHECE</span><h2>O atendimento termina.<br />O relacionamento<br /><em>não deveria.</em></h2><p>Entre a consulta de hoje e o próximo retorno, há muitas oportunidades de estar presente.</p></div><div className="problem-list">{[['01', 'Quem acompanha depois da consulta?', 'Sem uma rotina de contato, o paciente fica distante e a equipe perde o momento de saber como ele está.', 'Acompanhamento no momento certo'], ['02', 'Quem lembra que está na hora de voltar?', 'O retorno recomendado se perde no dia a dia. O paciente esquece, e a clínica perde a oportunidade de continuar o cuidado.', 'Oportunidades que ganham visibilidade'], ['03', 'Quem lembra de tudo, por todos?', 'Depender de anotações e da memória da recepção transforma cada próximo passo em mais uma tarefa manual.', 'Uma equipe com contexto para agir']].map(([number, title, copy, resolution]) => <article key={number}><span className="problem-number">{number}</span><div><h3>{title}</h3><p>{copy}</p><span className="resolution"><Icon name="arrow" size={15} />{resolution}</span></div></article>)}</div></section>
      <section className="product-section" id="produto"><div className="site-container"><div className="product-intro"><div><span className="section-label">CONHEÇA O CLINISIS</span><h2>O pós-atendimento que trabalha<br />enquanto sua equipe atende.</h2></div><p>Quem precisa de atenção, quando entrar em contato e qual é o próximo passo. Explore a experiência abaixo.</p></div><ProductDemo /><div className="product-pillars">{[['message', 'Acompanhe', 'Mensagens e contexto para manter o paciente próximo.'], ['people', 'Recupere', 'Oportunidades para quem deveria voltar à clínica.'], ['journey', 'Relacione', 'Jornadas que dão continuidade a cada atendimento.'], ['chart', 'Entenda', 'Visibilidade do contato ao retorno realizado.']].map(([icon, title, text]) => <article key={title}><Icon name={icon} /><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
      <section className="site-container how-section" id="como-funciona"><div className="centered-heading"><span className="section-label">SIMPLES PARA SUA EQUIPE. PRÓXIMO DO PACIENTE.</span><h2>Cada consulta é o começo<br />de uma nova jornada.</h2><p>O Clinisis organiza a continuidade. Sua equipe cuida das relações.</p></div><ol className="how-steps">{journeySteps.map(([icon, title, , text], i) => <li key={title}><div className="step-icon"><Icon name={icon} size={24} /><span>0{i + 1}</span></div><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
      <section className="site-container integration-section" id="integracoes"><div className="integration-copy"><span className="section-label">SEU SISTEMA CONTINUA. SEU RELACIONAMENTO EVOLUI.</span><h2>Você não precisa<br />começar do zero.</h2><p>O Clinisis foi pensado para ser uma camada de relacionamento sobre a operação que a sua clínica já tem.</p><p>Seu sistema organiza os atendimentos. O Clinisis ajuda a organizar o que vem depois.</p><div className="integration-tags"><span>Cadastro manual</span><span>CSV</span><span>API</span><span>Webhooks</span></div><small>Formas de entrada previstas no MVP. Compatibilidade e disponibilidade de integrações sujeitas à validação.</small></div><div className="integration-diagram" aria-label="Fluxo: sistema da clínica, Clinisis, acompanhamento e paciente"><div className="integration-source"><Icon name="grid" size={25} /><strong>O sistema da sua clínica</strong><span>Pacientes · Atendimentos · Retornos</span></div><div className="connector-line"><span>Dados que viram relacionamento</span></div><div className="integration-hub"><Brand /><span>O próximo passo de cada paciente</span></div><div className="connector-line" /><div className="integration-destinations"><div><Icon name="message" /><span>Acompanhamento</span></div><div><Icon name="people" /><span>Paciente próximo</span></div><div><Icon name="calendar" /><span>Novo retorno</span></div></div></div></section>
      <section className="site-container faq-section" id="duvidas"><div><span className="section-label">VAMOS DEIXAR MAIS CLARO</span><h2>Boas perguntas.<br />Próximos passos.</h2><p>Entenda como o Clinisis se encaixa na rotina da sua clínica.</p></div><div className="faq-items">{faqs.map(([question, answer]) => <details key={question}><summary>{question}<Icon name="plus" size={18} /></summary><p>{answer}</p></details>)}</div></section>
      <section className="closing-section"><div className="site-container closing-inner"><span className="section-label">MAIS PRESENÇA. MAIS CONTINUIDADE.</span><h2>A consulta termina.<br /><span>O relacionamento continua.</span></h2><p>Dê a cada paciente um próximo passo.<br />E à sua clínica, uma nova oportunidade de cuidar.</p><a className="button button-mint" href="#produto">Quero conhecer o sistema <Icon name="arrow" size={18} /></a><span className="closing-note">Explore a demonstração do Clinisis.</span></div></section>
    </main>
    <footer className="site-footer site-container"><div><a className="brand-link" href="#inicio" aria-label="Clinisis — início"><Brand /></a><p>Tecnologia que mantém sua clínica<br />conectada aos pacientes.</p></div><nav aria-label="Links do rodapé"><a href="#produto">Produto</a><a href="#como-funciona">Como funciona</a><a href="#duvidas">Dúvidas</a>{appUrl && <a href={appUrl}>Entrar no sistema <Icon name="arrow" size={14} /></a>}</nav><div className="footer-bottom"><span>© {new Date().getFullYear()} Clinisis.</span><span>Feito para o que vem depois da consulta.</span></div></footer>
  </div>
}
